-- MySQL Script generated by MySQL Workbench
-- Sun Sep  8 15:41:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SAM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SAM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SAM` DEFAULT CHARACTER SET utf8 ;
USE `SAM` ;

-- -----------------------------------------------------
-- Table `SAM`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAM`.`Area` (
  `Sigla` CHAR(16) NOT NULL,
  ` Nome` VARCHAR(255) NULL,
  `SuperArea` CHAR(16) NOT NULL,
  PRIMARY KEY (`Sigla`),
  INDEX `fk_Area_Area1_idx` (`SuperArea` ASC) VISIBLE,
  CONSTRAINT `fk_Area_Area1`
    FOREIGN KEY (`SuperArea`)
    REFERENCES `SAM`.`Area` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAM`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAM`.`Curso` (
  `Sigla` CHAR(16) NOT NULL,
  ` Nome` VARCHAR(255) NULL,
  `Horas` TIME NULL,
  `Custo` DOUBLE NULL,
  `Area` CHAR(16) NOT NULL,
  PRIMARY KEY (`Sigla`),
  INDEX `fk_Curso_Area_idx` (`Area` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_Area`
    FOREIGN KEY (`Area`)
    REFERENCES `SAM`.`Area` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAM`.`Modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAM`.`Modulo` (
  `Sigla` CHAR(16) NOT NULL,
  ` Nome` VARCHAR(255) NULL,
  `Curso` CHAR(16) NOT NULL,
  PRIMARY KEY (`Sigla`),
  INDEX `fk_Modulo_Curso1_idx` (`Curso` ASC) VISIBLE,
  CONSTRAINT `fk_Modulo_Curso1`
    FOREIGN KEY (`Curso`)
    REFERENCES `SAM`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAM`.`Topico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAM`.`Topico` (
  `Sigla` CHAR(16) NOT NULL,
  ` Nome` VARCHAR(255) NULL,
  `Horas` TIME NULL,
  `Modulo` CHAR(16) NOT NULL,
  PRIMARY KEY (`Sigla`, `Modulo`),
  INDEX `fk_Topico_Modulo1_idx` (`Modulo` ASC) VISIBLE,
  CONSTRAINT `fk_Topico_Modulo1`
    FOREIGN KEY (`Modulo`)
    REFERENCES `SAM`.`Modulo` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAM`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAM`.`Aluno` (
  `CPF` CHAR(11) NOT NULL,
  ` Nome` VARCHAR(255) NULL,
  `Sobrenome` VARCHAR(255) NULL,
  `Sexo` ENUM('M', 'F', 'Outro') NULL,
  `DataNasc` DATETIME NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAM`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAM`.`Professor` (
  `CPF` VARCHAR(11) NOT NULL,
  ` Nome` VARCHAR(255) NULL,
  `Curso` CHAR(16) NOT NULL,
  PRIMARY KEY (`CPF`),
  INDEX `fk_Professor_Curso1_idx` (`Curso` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Curso1`
    FOREIGN KEY (`Curso`)
    REFERENCES `SAM`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAM`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAM`.`Matricula` (
  `Curso` CHAR(16) NOT NULL,
  `Aluno` INT NOT NULL,
  `Data` DATETIME NULL,
  `Pago` INT NULL,
  PRIMARY KEY (`Curso`, `Aluno`),
  INDEX `fk_Curso_has_Aluno_Aluno1_idx` (`Aluno` ASC) VISIBLE,
  INDEX `fk_Curso_has_Aluno_Curso1_idx` (`Curso` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_has_Aluno_Curso1`
    FOREIGN KEY (`Curso`)
    REFERENCES `SAM`.`Curso` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno`)
    REFERENCES `SAM`.`Aluno` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
